# Generated by Django 3.0.3 on 2020-04-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200410_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='/static/image/default.jpg', upload_to='static/image/'),
        ),
    ]
