# Generated by Django 3.0.3 on 2020-05-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='/static/image/default.jpg', upload_to='avatars/'),
        ),
    ]
