# Generated by Django 3.0.3 on 2020-06-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200515_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='昵称'),
        ),
    ]
